---
- name: Project
  hosts: localhost
  become: yes

  tasks:
  - name: update
    apt: update_cache=yes force_apt_get=yes

  - name: java11
    apt:
      name: openjdk-11-jdk
      state: present

  - name: maven
    apt:
      name: maven
      state: present

  - name: Create a directory Tomcat
    file:
      path: "/opt/tomcat"
      state: directory
      mode: '0755'

  - name : Download and install tomcat
    unarchive:
      src: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.79/bin/apache-tomcat-8.5.79.tar.gz"
      dest: "/opt/tomcat/"
      mode: 0755
      remote_src: yes

  - name: Recursively change ownership of a directory
    file:
      path: "/opt/tomcat"
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

  - name: sed commands for Tomcat
    shell: sed -i '56 i <!-- user manager can access only manager section -->\n<role rolename="manager-gui" />\n<user username="manager" password="manager" roles="manager-gui" />\n\n<!-- user admin can access manager and admin section both -->\n<role rolename="admin-gui" />\n<user username="admin" password="admin" roles="manager-gui,admin-gui" />' /opt/tomcat/apache-tomcat-8.5.79/conf/tomcat-users.xml
    shell: "sed -i '21 i <!--' /opt/tomcat/apache-tomcat-8.5.79/webapps/manager/META-INF/context.xml"
    shell: "sed -i '24 i -->' /opt/tomcat/apache-tomcat-8.5.79/webapps/manager/META-INF/context.xml"
    shell: "sed -i '21 i <!--' /opt/tomcat/apache-tomcat-8.5.79/webapps/host-manager/META-INF/context.xml"
    shell: "sed -i '24 i -->' /opt/tomcat/apache-tomcat-8.5.79/webapps/host-manager/META-INF/context.xml"

  - name: mv file
    command: mv /Geocit134/tomcat.service /etc/systemd/system

  - name: start Tomcat
    systemd:
      daemon_reload: yes
      state: started
      name: tomcat
      enabled: yes

  - name: sed commands for project
    shell: "sed -i 's/postusername/${DB_USER}/g' /Geocit134/src/main/resources/application.properties"
    shell: "sed -i 's/postpassword/${DB_PASS}/g' /Geocit134/src/main/resources/application.properties"
    shell: "sed -i 's/localhost:5432/${DB_URL}:5432/g' /Geocit134/src/main/resources/application.properties"
    shell: "sed -i 's/passwordemail/${EMAIL_PASS}/g' /Geocit134/src/main/resources/application.properties"

  - name: build
    shell: "cd /Geocit134 && mvn clean install"

  - name: mv war
    command: mv /Geocit134/target/citizen.war /opt/tomcat/apache-tomcat-8.5.79/webapps/

  - name: start Tomcat
    shell: "/opt/tomcat/apache-tomcat-8.5.79/bin/startup.sh"
